# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Slack notify
        uses: sushmithaeshwar/composite-gha-action@v1
        if: always()
        with:
          channel-id: gha
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Run a one-line script
        run: ech Hello, world!
          
