# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Run a one-line script
        run: ech Hello, world!
        
  notify:
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
     - name: Slack notify workflow run status
       uses: sushmithaeshwar/composite-gha-action@v1
       with:
         channel-id: gha
         slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
